//TODO Sort all of these
class NekosLifeEndpoints {
  static const List<String> sfw = [
    'femdom', 
    'tickle', 
    'classic', 
    'ngif', 
    'erofeet', 
    'meow', 
    'erok', 
    'poke', 
    'les', 
    'v3', 
    'hololewd', 
    'nekoapi_v3.1', 
    'lewdk', 
    'keta', 
    'feetg', 
    'nsfw_neko_gif', 
    'eroyuri', 
    'kiss', 
    '8ball', 
    'kuni', 
    'tits', 
    'pussy_jpg', 
    'cum_jpg', 
    'pussy', 
    'lewdkemo', 
    'lizard', 
    'slap', 
    'cuddle', 
    'spank', 
    'smallboobs', 
    'goose', 
    'Random_hentai_gif', 
    'avatar', 
    'fox_girl', 
    'nsfw_avatar', 
    'hug', 
    'gecg', 
    'boobs', 
    'pat', 
    'feet', 
    'smug', 
    'kemonomimi', 
    'solog', 
    'holo', 
    'wallpaper', 
    'bj', 
    'woof', 
    'yuri', 
    'trap', 
    'baka', 
    'holoero', 
    'feed', 
    'neko', 
    'gasm',  
    'futanari',
    'solo', 
    'waifu', 
    'pwankg', 
    'eron', 
    'erokemo',
  ];
  static const List<String> nsfw = [
    'lewd',
    'cum',
    'ero',
    'hentai',
    'anal', 
    'blowjob', 
  ];
  static List<String> getAvailableTags({bool includeNsfw = true}) {
    List<String> tags = new List.from(sfw, growable: true);
    if(includeNsfw) tags.addAll(nsfw);
    return tags;
  }
}